[db]
   name = "store_user"
   user = "root"
   password = "password"
   host = "192.168.3.2:3306"
   charset = "utf8mb4"
   debug =  true
[aliyun]
    endpoint = "http://oss-cn-hangzhou.aliyuncs.com"
    accessKeyId = "LTAI4FgL4Ew4kGTSEWQ8gSbo"
    accessKeySecret = "ZElyfnMQ4E4tE8QKJeXdZmgJ54Mgea"
    bucketName = "weflare"
    bucketHost = "http://weflare.oss-cn-hangzhou.aliyuncs.com"