// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package srv_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Enabled int32

const (
	Enabled_No  Enabled = 0
	Enabled_Yes Enabled = 1
)

var Enabled_name = map[int32]string{
	0: "No",
	1: "Yes",
}

var Enabled_value = map[string]int32{
	"No":  0,
	"Yes": 1,
}

func (x Enabled) String() string {
	return proto.EnumName(Enabled_name, int32(x))
}

func (Enabled) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

type Pagination struct {
	Total                int32    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Condition            []string `protobuf:"bytes,4,rep,name=condition,proto3" json:"condition,omitempty"`
	Order                []string `protobuf:"bytes,5,rep,name=order,proto3" json:"order,omitempty"`
	Group                []string `protobuf:"bytes,6,rep,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pagination) Reset()         { *m = Pagination{} }
func (m *Pagination) String() string { return proto.CompactTextString(m) }
func (*Pagination) ProtoMessage()    {}
func (*Pagination) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

func (m *Pagination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pagination.Unmarshal(m, b)
}
func (m *Pagination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pagination.Marshal(b, m, deterministic)
}
func (m *Pagination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pagination.Merge(m, src)
}
func (m *Pagination) XXX_Size() int {
	return xxx_messageInfo_Pagination.Size(m)
}
func (m *Pagination) XXX_DiscardUnknown() {
	xxx_messageInfo_Pagination.DiscardUnknown(m)
}

var xxx_messageInfo_Pagination proto.InternalMessageInfo

func (m *Pagination) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Pagination) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Pagination) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Pagination) GetCondition() []string {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (m *Pagination) GetOrder() []string {
	if m != nil {
		return m.Order
	}
	return nil
}

func (m *Pagination) GetGroup() []string {
	if m != nil {
		return m.Group
	}
	return nil
}

type Resource struct {
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Id                   int32                `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Nickname             string               `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Realname             string               `protobuf:"bytes,6,opt,name=realname,proto3" json:"realname,omitempty"`
	Mobile               string               `protobuf:"bytes,7,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Email                string               `protobuf:"bytes,8,opt,name=email,proto3" json:"email,omitempty"`
	Code                 string               `protobuf:"bytes,9,opt,name=code,proto3" json:"code,omitempty"`
	Source               string               `protobuf:"bytes,10,opt,name=source,proto3" json:"source,omitempty"`
	Birthday             *timestamp.Timestamp `protobuf:"bytes,11,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Enabled              Enabled              `protobuf:"varint,12,opt,name=enabled,proto3,enum=srv.user.Enabled" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Resource) Reset()         { *m = Resource{} }
func (m *Resource) String() string { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()    {}
func (*Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{1}
}

func (m *Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resource.Unmarshal(m, b)
}
func (m *Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resource.Marshal(b, m, deterministic)
}
func (m *Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resource.Merge(m, src)
}
func (m *Resource) XXX_Size() int {
	return xxx_messageInfo_Resource.Size(m)
}
func (m *Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_Resource proto.InternalMessageInfo

func (m *Resource) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Resource) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Resource) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Resource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Resource) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *Resource) GetRealname() string {
	if m != nil {
		return m.Realname
	}
	return ""
}

func (m *Resource) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *Resource) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Resource) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Resource) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Resource) GetBirthday() *timestamp.Timestamp {
	if m != nil {
		return m.Birthday
	}
	return nil
}

func (m *Resource) GetEnabled() Enabled {
	if m != nil {
		return m.Enabled
	}
	return Enabled_No
}

type List struct {
	Data                 []*Resource `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *List) Reset()         { *m = List{} }
func (m *List) String() string { return proto.CompactTextString(m) }
func (*List) ProtoMessage()    {}
func (*List) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{2}
}

func (m *List) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_List.Unmarshal(m, b)
}
func (m *List) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_List.Marshal(b, m, deterministic)
}
func (m *List) XXX_Merge(src proto.Message) {
	xxx_messageInfo_List.Merge(m, src)
}
func (m *List) XXX_Size() int {
	return xxx_messageInfo_List.Size(m)
}
func (m *List) XXX_DiscardUnknown() {
	xxx_messageInfo_List.DiscardUnknown(m)
}

var xxx_messageInfo_List proto.InternalMessageInfo

func (m *List) GetData() []*Resource {
	if m != nil {
		return m.Data
	}
	return nil
}

type ShowRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowRequest) Reset()         { *m = ShowRequest{} }
func (m *ShowRequest) String() string { return proto.CompactTextString(m) }
func (*ShowRequest) ProtoMessage()    {}
func (*ShowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{3}
}

func (m *ShowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowRequest.Unmarshal(m, b)
}
func (m *ShowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowRequest.Marshal(b, m, deterministic)
}
func (m *ShowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowRequest.Merge(m, src)
}
func (m *ShowRequest) XXX_Size() int {
	return xxx_messageInfo_ShowRequest.Size(m)
}
func (m *ShowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShowRequest proto.InternalMessageInfo

func (m *ShowRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ShowResponse struct {
	Data                 *Resource `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ShowResponse) Reset()         { *m = ShowResponse{} }
func (m *ShowResponse) String() string { return proto.CompactTextString(m) }
func (*ShowResponse) ProtoMessage()    {}
func (*ShowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{4}
}

func (m *ShowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowResponse.Unmarshal(m, b)
}
func (m *ShowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowResponse.Marshal(b, m, deterministic)
}
func (m *ShowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowResponse.Merge(m, src)
}
func (m *ShowResponse) XXX_Size() int {
	return xxx_messageInfo_ShowResponse.Size(m)
}
func (m *ShowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShowResponse proto.InternalMessageInfo

func (m *ShowResponse) GetData() *Resource {
	if m != nil {
		return m.Data
	}
	return nil
}

type MobileRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MobileRequest) Reset()         { *m = MobileRequest{} }
func (m *MobileRequest) String() string { return proto.CompactTextString(m) }
func (*MobileRequest) ProtoMessage()    {}
func (*MobileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{5}
}

func (m *MobileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MobileRequest.Unmarshal(m, b)
}
func (m *MobileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MobileRequest.Marshal(b, m, deterministic)
}
func (m *MobileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MobileRequest.Merge(m, src)
}
func (m *MobileRequest) XXX_Size() int {
	return xxx_messageInfo_MobileRequest.Size(m)
}
func (m *MobileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MobileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MobileRequest proto.InternalMessageInfo

func (m *MobileRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

type MobileResponse struct {
	Data                 *Resource `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MobileResponse) Reset()         { *m = MobileResponse{} }
func (m *MobileResponse) String() string { return proto.CompactTextString(m) }
func (*MobileResponse) ProtoMessage()    {}
func (*MobileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{6}
}

func (m *MobileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MobileResponse.Unmarshal(m, b)
}
func (m *MobileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MobileResponse.Marshal(b, m, deterministic)
}
func (m *MobileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MobileResponse.Merge(m, src)
}
func (m *MobileResponse) XXX_Size() int {
	return xxx_messageInfo_MobileResponse.Size(m)
}
func (m *MobileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MobileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MobileResponse proto.InternalMessageInfo

func (m *MobileResponse) GetData() *Resource {
	if m != nil {
		return m.Data
	}
	return nil
}

type MobileCreateRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mobile               string   `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Source               string   `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MobileCreateRequest) Reset()         { *m = MobileCreateRequest{} }
func (m *MobileCreateRequest) String() string { return proto.CompactTextString(m) }
func (*MobileCreateRequest) ProtoMessage()    {}
func (*MobileCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{7}
}

func (m *MobileCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MobileCreateRequest.Unmarshal(m, b)
}
func (m *MobileCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MobileCreateRequest.Marshal(b, m, deterministic)
}
func (m *MobileCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MobileCreateRequest.Merge(m, src)
}
func (m *MobileCreateRequest) XXX_Size() int {
	return xxx_messageInfo_MobileCreateRequest.Size(m)
}
func (m *MobileCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MobileCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MobileCreateRequest proto.InternalMessageInfo

func (m *MobileCreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MobileCreateRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *MobileCreateRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *MobileCreateRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

type MobileCreateResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MobileCreateResponse) Reset()         { *m = MobileCreateResponse{} }
func (m *MobileCreateResponse) String() string { return proto.CompactTextString(m) }
func (*MobileCreateResponse) ProtoMessage()    {}
func (*MobileCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{8}
}

func (m *MobileCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MobileCreateResponse.Unmarshal(m, b)
}
func (m *MobileCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MobileCreateResponse.Marshal(b, m, deterministic)
}
func (m *MobileCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MobileCreateResponse.Merge(m, src)
}
func (m *MobileCreateResponse) XXX_Size() int {
	return xxx_messageInfo_MobileCreateResponse.Size(m)
}
func (m *MobileCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MobileCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MobileCreateResponse proto.InternalMessageInfo

func (m *MobileCreateResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ModifyPassRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyPassRequest) Reset()         { *m = ModifyPassRequest{} }
func (m *ModifyPassRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyPassRequest) ProtoMessage()    {}
func (*ModifyPassRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{9}
}

func (m *ModifyPassRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyPassRequest.Unmarshal(m, b)
}
func (m *ModifyPassRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyPassRequest.Marshal(b, m, deterministic)
}
func (m *ModifyPassRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyPassRequest.Merge(m, src)
}
func (m *ModifyPassRequest) XXX_Size() int {
	return xxx_messageInfo_ModifyPassRequest.Size(m)
}
func (m *ModifyPassRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyPassRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyPassRequest proto.InternalMessageInfo

func (m *ModifyPassRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ModifyPassRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ModifyPassResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyPassResponse) Reset()         { *m = ModifyPassResponse{} }
func (m *ModifyPassResponse) String() string { return proto.CompactTextString(m) }
func (*ModifyPassResponse) ProtoMessage()    {}
func (*ModifyPassResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{10}
}

func (m *ModifyPassResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyPassResponse.Unmarshal(m, b)
}
func (m *ModifyPassResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyPassResponse.Marshal(b, m, deterministic)
}
func (m *ModifyPassResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyPassResponse.Merge(m, src)
}
func (m *ModifyPassResponse) XXX_Size() int {
	return xxx_messageInfo_ModifyPassResponse.Size(m)
}
func (m *ModifyPassResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyPassResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyPassResponse proto.InternalMessageInfo

func (m *ModifyPassResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ModifyMobileRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyMobileRequest) Reset()         { *m = ModifyMobileRequest{} }
func (m *ModifyMobileRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyMobileRequest) ProtoMessage()    {}
func (*ModifyMobileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{11}
}

func (m *ModifyMobileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyMobileRequest.Unmarshal(m, b)
}
func (m *ModifyMobileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyMobileRequest.Marshal(b, m, deterministic)
}
func (m *ModifyMobileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyMobileRequest.Merge(m, src)
}
func (m *ModifyMobileRequest) XXX_Size() int {
	return xxx_messageInfo_ModifyMobileRequest.Size(m)
}
func (m *ModifyMobileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyMobileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyMobileRequest proto.InternalMessageInfo

func (m *ModifyMobileRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ModifyMobileRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ModifyMobileResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyMobileResponse) Reset()         { *m = ModifyMobileResponse{} }
func (m *ModifyMobileResponse) String() string { return proto.CompactTextString(m) }
func (*ModifyMobileResponse) ProtoMessage()    {}
func (*ModifyMobileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{12}
}

func (m *ModifyMobileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyMobileResponse.Unmarshal(m, b)
}
func (m *ModifyMobileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyMobileResponse.Marshal(b, m, deterministic)
}
func (m *ModifyMobileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyMobileResponse.Merge(m, src)
}
func (m *ModifyMobileResponse) XXX_Size() int {
	return xxx_messageInfo_ModifyMobileResponse.Size(m)
}
func (m *ModifyMobileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyMobileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyMobileResponse proto.InternalMessageInfo

func (m *ModifyMobileResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{13}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

func init() {
	proto.RegisterEnum("srv.user.Enabled", Enabled_name, Enabled_value)
	proto.RegisterType((*Pagination)(nil), "srv.user.Pagination")
	proto.RegisterType((*Resource)(nil), "srv.user.Resource")
	proto.RegisterType((*List)(nil), "srv.user.List")
	proto.RegisterType((*ShowRequest)(nil), "srv.user.ShowRequest")
	proto.RegisterType((*ShowResponse)(nil), "srv.user.ShowResponse")
	proto.RegisterType((*MobileRequest)(nil), "srv.user.MobileRequest")
	proto.RegisterType((*MobileResponse)(nil), "srv.user.MobileResponse")
	proto.RegisterType((*MobileCreateRequest)(nil), "srv.user.MobileCreateRequest")
	proto.RegisterType((*MobileCreateResponse)(nil), "srv.user.MobileCreateResponse")
	proto.RegisterType((*ModifyPassRequest)(nil), "srv.user.ModifyPassRequest")
	proto.RegisterType((*ModifyPassResponse)(nil), "srv.user.ModifyPassResponse")
	proto.RegisterType((*ModifyMobileRequest)(nil), "srv.user.ModifyMobileRequest")
	proto.RegisterType((*ModifyMobileResponse)(nil), "srv.user.ModifyMobileResponse")
	proto.RegisterType((*Message)(nil), "srv.user.Message")
}

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor_9b283a848145d6b7) }

var fileDescriptor_9b283a848145d6b7 = []byte{
	// 694 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xcf, 0x6f, 0xd3, 0x4a,
	0x10, 0xae, 0x63, 0x27, 0xb1, 0x27, 0x7d, 0x51, 0xbb, 0xaf, 0xed, 0x5b, 0xb9, 0xed, 0x23, 0xf2,
	0xa1, 0x44, 0x20, 0x39, 0x28, 0x48, 0xa5, 0x37, 0xa8, 0x10, 0x42, 0x08, 0x02, 0x95, 0x81, 0x03,
	0xc7, 0x8d, 0xbd, 0x4d, 0x2d, 0x12, 0xaf, 0xf1, 0xda, 0x94, 0xf2, 0x77, 0x70, 0xe1, 0xc4, 0xbf,
	0x8a, 0x76, 0xd7, 0xeb, 0x1f, 0x81, 0x52, 0x55, 0x5c, 0xac, 0x9d, 0xf9, 0x66, 0xbf, 0xd9, 0xf9,
	0xe6, 0x93, 0x61, 0x37, 0xcd, 0x58, 0xce, 0x26, 0x05, 0xa7, 0x99, 0xfc, 0xf8, 0x32, 0x46, 0x36,
	0xcf, 0x3e, 0xfb, 0x22, 0x76, 0xef, 0x2c, 0x18, 0x5b, 0x2c, 0xe9, 0x44, 0xe6, 0xe7, 0xc5, 0xf9,
	0x24, 0x8f, 0x57, 0x94, 0xe7, 0x64, 0x95, 0xaa, 0x52, 0xef, 0x9b, 0x01, 0x70, 0x46, 0x16, 0x71,
	0x42, 0xf2, 0x98, 0x25, 0x68, 0x07, 0xba, 0x39, 0xcb, 0xc9, 0x12, 0x1b, 0x23, 0x63, 0xdc, 0x0d,
	0x54, 0x80, 0x10, 0x58, 0x29, 0x59, 0x50, 0xdc, 0x91, 0x49, 0x79, 0x16, 0x39, 0x1e, 0x7f, 0xa5,
	0xd8, 0x54, 0x39, 0x71, 0x46, 0x07, 0xe0, 0x84, 0x2c, 0x89, 0x62, 0x41, 0x85, 0xad, 0x91, 0x39,
	0x76, 0x82, 0x3a, 0x21, 0xb8, 0x59, 0x16, 0xd1, 0x0c, 0x77, 0x25, 0xa2, 0x02, 0x91, 0x5d, 0x64,
	0xac, 0x48, 0x71, 0x4f, 0x65, 0x65, 0xe0, 0x7d, 0x37, 0xc1, 0x0e, 0x28, 0x67, 0x45, 0x16, 0x52,
	0x74, 0x02, 0x4e, 0x98, 0x51, 0x92, 0xd3, 0xe8, 0x34, 0x97, 0x0f, 0x1b, 0x4c, 0x5d, 0x5f, 0x0d,
	0xe6, 0xeb, 0xc1, 0xfc, 0x77, 0x7a, 0xb0, 0xa0, 0x2e, 0x16, 0x37, 0x8b, 0x34, 0x2a, 0x6f, 0x76,
	0x6e, 0xbe, 0x59, 0x15, 0xa3, 0x21, 0x74, 0xe2, 0xa8, 0x1c, 0xae, 0x13, 0x47, 0x62, 0xdc, 0x84,
	0xac, 0x28, 0xb6, 0x46, 0xc6, 0xd8, 0x09, 0xe4, 0x19, 0xb9, 0x60, 0x27, 0x71, 0xf8, 0x51, 0xe6,
	0xbb, 0x32, 0x5f, 0xc5, 0x02, 0xcb, 0x28, 0x59, 0x4a, 0xac, 0xa7, 0x30, 0x1d, 0xa3, 0x3d, 0xe8,
	0xad, 0xd8, 0x3c, 0x5e, 0x52, 0xdc, 0x97, 0x48, 0x19, 0x09, 0x29, 0xe8, 0x8a, 0xc4, 0x4b, 0x6c,
	0xcb, 0xb4, 0x0a, 0x44, 0xe7, 0x90, 0x45, 0x14, 0x3b, 0xaa, 0xb3, 0x38, 0x0b, 0x06, 0xa5, 0x0d,
	0x06, 0xc5, 0x50, 0x2a, 0x75, 0x0c, 0xf6, 0x3c, 0xce, 0xf2, 0x8b, 0x88, 0x5c, 0xe1, 0xc1, 0x8d,
	0xe3, 0x56, 0xb5, 0xe8, 0x3e, 0xf4, 0x69, 0x42, 0xe6, 0x4b, 0x1a, 0xe1, 0xcd, 0x91, 0x31, 0x1e,
	0x4e, 0xb7, 0x7d, 0x6d, 0x21, 0xff, 0x99, 0x02, 0x02, 0x5d, 0xe1, 0xf9, 0x60, 0xbd, 0x8a, 0x79,
	0x8e, 0x8e, 0xc0, 0x8a, 0x48, 0x4e, 0xb0, 0x31, 0x32, 0xc7, 0x83, 0x29, 0xaa, 0x6f, 0xe8, 0xc5,
	0x05, 0x12, 0xf7, 0x0e, 0x61, 0xf0, 0xf6, 0x82, 0x5d, 0x06, 0xf4, 0x53, 0x41, 0xb9, 0x56, 0xd6,
	0xd0, 0xca, 0x7a, 0xc7, 0xb0, 0xa9, 0x60, 0x9e, 0xb2, 0x84, 0xd3, 0x06, 0xad, 0xf1, 0x47, 0xda,
	0xbb, 0xf0, 0xcf, 0x4c, 0xea, 0xa6, 0x89, 0x6b, 0x59, 0x8d, 0xa6, 0xac, 0xde, 0x09, 0x0c, 0x75,
	0xe1, 0x2d, 0x5b, 0x14, 0xf0, 0xaf, 0xba, 0xf9, 0x54, 0x3a, 0x4a, 0x37, 0xd2, 0x5e, 0x30, 0x1a,
	0x5e, 0xa8, 0x9b, 0x77, 0x5a, 0x3b, 0x75, 0xc1, 0x4e, 0x09, 0xe7, 0x97, 0x2c, 0x53, 0x6e, 0x72,
	0x82, 0x2a, 0x6e, 0x6c, 0xd1, 0x6a, 0x6e, 0xd1, 0x3b, 0x82, 0x9d, 0x76, 0xdb, 0xf2, 0xd9, 0xeb,
	0xca, 0x3d, 0x86, 0xed, 0x19, 0x8b, 0xe2, 0xf3, 0xab, 0x33, 0xc2, 0xf9, 0x35, 0xf2, 0xb6, 0x1e,
	0xd0, 0x69, 0x3f, 0xc0, 0xf3, 0x01, 0x35, 0x09, 0xca, 0x36, 0x18, 0xfa, 0xbc, 0x08, 0x43, 0xca,
	0xb9, 0xa4, 0xb1, 0x03, 0x1d, 0x7a, 0xa7, 0x42, 0x0f, 0x51, 0xdf, 0x16, 0xfe, 0x36, 0x2d, 0x1f,
	0x88, 0xd9, 0x9a, 0x14, 0x37, 0x36, 0xdd, 0x87, 0xfe, 0x8c, 0x72, 0x2e, 0xfe, 0x39, 0x5b, 0x60,
	0x72, 0x72, 0x55, 0xea, 0x2e, 0x8e, 0xf7, 0x5c, 0xe8, 0x97, 0xfe, 0x44, 0x3d, 0xe8, 0xbc, 0x66,
	0x5b, 0x1b, 0xa8, 0x0f, 0xe6, 0x07, 0xca, 0xb7, 0x8c, 0xe9, 0x0f, 0x13, 0xac, 0xf7, 0x9c, 0x66,
	0x68, 0x02, 0xdd, 0x17, 0x49, 0x44, 0xbf, 0xa0, 0x9d, 0x7a, 0xd3, 0xf5, 0x3f, 0xcf, 0x1d, 0xd6,
	0x59, 0xe1, 0x6b, 0x6f, 0x03, 0x3d, 0x02, 0x4b, 0x58, 0x12, 0xed, 0xd6, 0x48, 0xc3, 0xc1, 0xee,
	0xde, 0x7a, 0x5a, 0xcd, 0xe0, 0x6d, 0xa0, 0x27, 0xe0, 0x3c, 0xa7, 0xb9, 0x1a, 0x0d, 0xfd, 0x57,
	0x97, 0xb5, 0xf4, 0x72, 0xf1, 0xaf, 0x40, 0xc5, 0xf0, 0x06, 0x36, 0x9b, 0xbb, 0x47, 0x87, 0xeb,
	0xb5, 0x2d, 0x2b, 0xba, 0xff, 0x5f, 0x07, 0x57, 0x84, 0x33, 0xe1, 0x7e, 0xbd, 0x63, 0x69, 0xbb,
	0xfd, 0xe6, 0x9d, 0x35, 0xfb, 0xb8, 0x07, 0xbf, 0x07, 0x2b, 0xba, 0x97, 0xe2, 0x7d, 0xf5, 0xfe,
	0xfe, 0x8a, 0x6c, 0xde, 0x93, 0x3f, 0xa5, 0x87, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x4e, 0x02,
	0xc8, 0xb9, 0xc7, 0x06, 0x00, 0x00,
}
