// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package srv_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Enabled int32

const (
	Enabled_No  Enabled = 0
	Enabled_Yes Enabled = 1
)

var Enabled_name = map[int32]string{
	0: "No",
	1: "Yes",
}

var Enabled_value = map[string]int32{
	"No":  0,
	"Yes": 1,
}

func (x Enabled) String() string {
	return proto.EnumName(Enabled_name, int32(x))
}

func (Enabled) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

type Pagination struct {
	Total                int32    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Condition            []string `protobuf:"bytes,4,rep,name=condition,proto3" json:"condition,omitempty"`
	Order                []string `protobuf:"bytes,5,rep,name=order,proto3" json:"order,omitempty"`
	Group                []string `protobuf:"bytes,6,rep,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pagination) Reset()         { *m = Pagination{} }
func (m *Pagination) String() string { return proto.CompactTextString(m) }
func (*Pagination) ProtoMessage()    {}
func (*Pagination) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

func (m *Pagination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pagination.Unmarshal(m, b)
}
func (m *Pagination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pagination.Marshal(b, m, deterministic)
}
func (m *Pagination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pagination.Merge(m, src)
}
func (m *Pagination) XXX_Size() int {
	return xxx_messageInfo_Pagination.Size(m)
}
func (m *Pagination) XXX_DiscardUnknown() {
	xxx_messageInfo_Pagination.DiscardUnknown(m)
}

var xxx_messageInfo_Pagination proto.InternalMessageInfo

func (m *Pagination) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Pagination) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Pagination) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Pagination) GetCondition() []string {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (m *Pagination) GetOrder() []string {
	if m != nil {
		return m.Order
	}
	return nil
}

func (m *Pagination) GetGroup() []string {
	if m != nil {
		return m.Group
	}
	return nil
}

type Resource struct {
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Id                   int32                `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Nickname             string               `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Realname             string               `protobuf:"bytes,6,opt,name=realname,proto3" json:"realname,omitempty"`
	Mobile               string               `protobuf:"bytes,7,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Email                string               `protobuf:"bytes,8,opt,name=email,proto3" json:"email,omitempty"`
	Code                 string               `protobuf:"bytes,9,opt,name=code,proto3" json:"code,omitempty"`
	Source               string               `protobuf:"bytes,10,opt,name=source,proto3" json:"source,omitempty"`
	Birthday             *timestamp.Timestamp `protobuf:"bytes,11,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Enabled              Enabled              `protobuf:"varint,12,opt,name=enabled,proto3,enum=srv.user.Enabled" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Resource) Reset()         { *m = Resource{} }
func (m *Resource) String() string { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()    {}
func (*Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{1}
}

func (m *Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resource.Unmarshal(m, b)
}
func (m *Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resource.Marshal(b, m, deterministic)
}
func (m *Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resource.Merge(m, src)
}
func (m *Resource) XXX_Size() int {
	return xxx_messageInfo_Resource.Size(m)
}
func (m *Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_Resource proto.InternalMessageInfo

func (m *Resource) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Resource) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Resource) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Resource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Resource) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *Resource) GetRealname() string {
	if m != nil {
		return m.Realname
	}
	return ""
}

func (m *Resource) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *Resource) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Resource) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Resource) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Resource) GetBirthday() *timestamp.Timestamp {
	if m != nil {
		return m.Birthday
	}
	return nil
}

func (m *Resource) GetEnabled() Enabled {
	if m != nil {
		return m.Enabled
	}
	return Enabled_No
}

type List struct {
	Data                 []*Resource `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *List) Reset()         { *m = List{} }
func (m *List) String() string { return proto.CompactTextString(m) }
func (*List) ProtoMessage()    {}
func (*List) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{2}
}

func (m *List) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_List.Unmarshal(m, b)
}
func (m *List) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_List.Marshal(b, m, deterministic)
}
func (m *List) XXX_Merge(src proto.Message) {
	xxx_messageInfo_List.Merge(m, src)
}
func (m *List) XXX_Size() int {
	return xxx_messageInfo_List.Size(m)
}
func (m *List) XXX_DiscardUnknown() {
	xxx_messageInfo_List.DiscardUnknown(m)
}

var xxx_messageInfo_List proto.InternalMessageInfo

func (m *List) GetData() []*Resource {
	if m != nil {
		return m.Data
	}
	return nil
}

type ShowRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowRequest) Reset()         { *m = ShowRequest{} }
func (m *ShowRequest) String() string { return proto.CompactTextString(m) }
func (*ShowRequest) ProtoMessage()    {}
func (*ShowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{3}
}

func (m *ShowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowRequest.Unmarshal(m, b)
}
func (m *ShowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowRequest.Marshal(b, m, deterministic)
}
func (m *ShowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowRequest.Merge(m, src)
}
func (m *ShowRequest) XXX_Size() int {
	return xxx_messageInfo_ShowRequest.Size(m)
}
func (m *ShowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShowRequest proto.InternalMessageInfo

func (m *ShowRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ShowResponse struct {
	Data                 *Resource `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ShowResponse) Reset()         { *m = ShowResponse{} }
func (m *ShowResponse) String() string { return proto.CompactTextString(m) }
func (*ShowResponse) ProtoMessage()    {}
func (*ShowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{4}
}

func (m *ShowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowResponse.Unmarshal(m, b)
}
func (m *ShowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowResponse.Marshal(b, m, deterministic)
}
func (m *ShowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowResponse.Merge(m, src)
}
func (m *ShowResponse) XXX_Size() int {
	return xxx_messageInfo_ShowResponse.Size(m)
}
func (m *ShowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShowResponse proto.InternalMessageInfo

func (m *ShowResponse) GetData() *Resource {
	if m != nil {
		return m.Data
	}
	return nil
}

type MobileRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MobileRequest) Reset()         { *m = MobileRequest{} }
func (m *MobileRequest) String() string { return proto.CompactTextString(m) }
func (*MobileRequest) ProtoMessage()    {}
func (*MobileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{5}
}

func (m *MobileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MobileRequest.Unmarshal(m, b)
}
func (m *MobileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MobileRequest.Marshal(b, m, deterministic)
}
func (m *MobileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MobileRequest.Merge(m, src)
}
func (m *MobileRequest) XXX_Size() int {
	return xxx_messageInfo_MobileRequest.Size(m)
}
func (m *MobileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MobileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MobileRequest proto.InternalMessageInfo

func (m *MobileRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

type MobileResponse struct {
	Data                 *Resource `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MobileResponse) Reset()         { *m = MobileResponse{} }
func (m *MobileResponse) String() string { return proto.CompactTextString(m) }
func (*MobileResponse) ProtoMessage()    {}
func (*MobileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{6}
}

func (m *MobileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MobileResponse.Unmarshal(m, b)
}
func (m *MobileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MobileResponse.Marshal(b, m, deterministic)
}
func (m *MobileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MobileResponse.Merge(m, src)
}
func (m *MobileResponse) XXX_Size() int {
	return xxx_messageInfo_MobileResponse.Size(m)
}
func (m *MobileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MobileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MobileResponse proto.InternalMessageInfo

func (m *MobileResponse) GetData() *Resource {
	if m != nil {
		return m.Data
	}
	return nil
}

type MobileRegisterRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mobile               string   `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Source               string   `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MobileRegisterRequest) Reset()         { *m = MobileRegisterRequest{} }
func (m *MobileRegisterRequest) String() string { return proto.CompactTextString(m) }
func (*MobileRegisterRequest) ProtoMessage()    {}
func (*MobileRegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{7}
}

func (m *MobileRegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MobileRegisterRequest.Unmarshal(m, b)
}
func (m *MobileRegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MobileRegisterRequest.Marshal(b, m, deterministic)
}
func (m *MobileRegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MobileRegisterRequest.Merge(m, src)
}
func (m *MobileRegisterRequest) XXX_Size() int {
	return xxx_messageInfo_MobileRegisterRequest.Size(m)
}
func (m *MobileRegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MobileRegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MobileRegisterRequest proto.InternalMessageInfo

func (m *MobileRegisterRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MobileRegisterRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *MobileRegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *MobileRegisterRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

type MobileRegisterResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MobileRegisterResponse) Reset()         { *m = MobileRegisterResponse{} }
func (m *MobileRegisterResponse) String() string { return proto.CompactTextString(m) }
func (*MobileRegisterResponse) ProtoMessage()    {}
func (*MobileRegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{8}
}

func (m *MobileRegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MobileRegisterResponse.Unmarshal(m, b)
}
func (m *MobileRegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MobileRegisterResponse.Marshal(b, m, deterministic)
}
func (m *MobileRegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MobileRegisterResponse.Merge(m, src)
}
func (m *MobileRegisterResponse) XXX_Size() int {
	return xxx_messageInfo_MobileRegisterResponse.Size(m)
}
func (m *MobileRegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MobileRegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MobileRegisterResponse proto.InternalMessageInfo

func (m *MobileRegisterResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ModifyPassRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OldPassword          string   `protobuf:"bytes,2,opt,name=oldPassword,proto3" json:"oldPassword,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyPassRequest) Reset()         { *m = ModifyPassRequest{} }
func (m *ModifyPassRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyPassRequest) ProtoMessage()    {}
func (*ModifyPassRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{9}
}

func (m *ModifyPassRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyPassRequest.Unmarshal(m, b)
}
func (m *ModifyPassRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyPassRequest.Marshal(b, m, deterministic)
}
func (m *ModifyPassRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyPassRequest.Merge(m, src)
}
func (m *ModifyPassRequest) XXX_Size() int {
	return xxx_messageInfo_ModifyPassRequest.Size(m)
}
func (m *ModifyPassRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyPassRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyPassRequest proto.InternalMessageInfo

func (m *ModifyPassRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ModifyPassRequest) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

func (m *ModifyPassRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ModifyPassResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyPassResponse) Reset()         { *m = ModifyPassResponse{} }
func (m *ModifyPassResponse) String() string { return proto.CompactTextString(m) }
func (*ModifyPassResponse) ProtoMessage()    {}
func (*ModifyPassResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{10}
}

func (m *ModifyPassResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyPassResponse.Unmarshal(m, b)
}
func (m *ModifyPassResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyPassResponse.Marshal(b, m, deterministic)
}
func (m *ModifyPassResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyPassResponse.Merge(m, src)
}
func (m *ModifyPassResponse) XXX_Size() int {
	return xxx_messageInfo_ModifyPassResponse.Size(m)
}
func (m *ModifyPassResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyPassResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyPassResponse proto.InternalMessageInfo

func (m *ModifyPassResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ModifyMobileRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OldMobile            string   `protobuf:"bytes,2,opt,name=oldMobile,proto3" json:"oldMobile,omitempty"`
	Mobile               string   `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyMobileRequest) Reset()         { *m = ModifyMobileRequest{} }
func (m *ModifyMobileRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyMobileRequest) ProtoMessage()    {}
func (*ModifyMobileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{11}
}

func (m *ModifyMobileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyMobileRequest.Unmarshal(m, b)
}
func (m *ModifyMobileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyMobileRequest.Marshal(b, m, deterministic)
}
func (m *ModifyMobileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyMobileRequest.Merge(m, src)
}
func (m *ModifyMobileRequest) XXX_Size() int {
	return xxx_messageInfo_ModifyMobileRequest.Size(m)
}
func (m *ModifyMobileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyMobileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyMobileRequest proto.InternalMessageInfo

func (m *ModifyMobileRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ModifyMobileRequest) GetOldMobile() string {
	if m != nil {
		return m.OldMobile
	}
	return ""
}

func (m *ModifyMobileRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

type ModifyMobileResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyMobileResponse) Reset()         { *m = ModifyMobileResponse{} }
func (m *ModifyMobileResponse) String() string { return proto.CompactTextString(m) }
func (*ModifyMobileResponse) ProtoMessage()    {}
func (*ModifyMobileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{12}
}

func (m *ModifyMobileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyMobileResponse.Unmarshal(m, b)
}
func (m *ModifyMobileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyMobileResponse.Marshal(b, m, deterministic)
}
func (m *ModifyMobileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyMobileResponse.Merge(m, src)
}
func (m *ModifyMobileResponse) XXX_Size() int {
	return xxx_messageInfo_ModifyMobileResponse.Size(m)
}
func (m *ModifyMobileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyMobileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyMobileResponse proto.InternalMessageInfo

func (m *ModifyMobileResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ResetPassRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPassRequest) Reset()         { *m = ResetPassRequest{} }
func (m *ResetPassRequest) String() string { return proto.CompactTextString(m) }
func (*ResetPassRequest) ProtoMessage()    {}
func (*ResetPassRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{13}
}

func (m *ResetPassRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPassRequest.Unmarshal(m, b)
}
func (m *ResetPassRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPassRequest.Marshal(b, m, deterministic)
}
func (m *ResetPassRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPassRequest.Merge(m, src)
}
func (m *ResetPassRequest) XXX_Size() int {
	return xxx_messageInfo_ResetPassRequest.Size(m)
}
func (m *ResetPassRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPassRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPassRequest proto.InternalMessageInfo

func (m *ResetPassRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ResetPassRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ResetPassResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPassResponse) Reset()         { *m = ResetPassResponse{} }
func (m *ResetPassResponse) String() string { return proto.CompactTextString(m) }
func (*ResetPassResponse) ProtoMessage()    {}
func (*ResetPassResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{14}
}

func (m *ResetPassResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPassResponse.Unmarshal(m, b)
}
func (m *ResetPassResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPassResponse.Marshal(b, m, deterministic)
}
func (m *ResetPassResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPassResponse.Merge(m, src)
}
func (m *ResetPassResponse) XXX_Size() int {
	return xxx_messageInfo_ResetPassResponse.Size(m)
}
func (m *ResetPassResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPassResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPassResponse proto.InternalMessageInfo

func (m *ResetPassResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type PassLoginRequest struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Source               string   `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PassLoginRequest) Reset()         { *m = PassLoginRequest{} }
func (m *PassLoginRequest) String() string { return proto.CompactTextString(m) }
func (*PassLoginRequest) ProtoMessage()    {}
func (*PassLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{15}
}

func (m *PassLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PassLoginRequest.Unmarshal(m, b)
}
func (m *PassLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PassLoginRequest.Marshal(b, m, deterministic)
}
func (m *PassLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PassLoginRequest.Merge(m, src)
}
func (m *PassLoginRequest) XXX_Size() int {
	return xxx_messageInfo_PassLoginRequest.Size(m)
}
func (m *PassLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PassLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PassLoginRequest proto.InternalMessageInfo

func (m *PassLoginRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *PassLoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *PassLoginRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

type PassLoginResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PassLoginResponse) Reset()         { *m = PassLoginResponse{} }
func (m *PassLoginResponse) String() string { return proto.CompactTextString(m) }
func (*PassLoginResponse) ProtoMessage()    {}
func (*PassLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{16}
}

func (m *PassLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PassLoginResponse.Unmarshal(m, b)
}
func (m *PassLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PassLoginResponse.Marshal(b, m, deterministic)
}
func (m *PassLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PassLoginResponse.Merge(m, src)
}
func (m *PassLoginResponse) XXX_Size() int {
	return xxx_messageInfo_PassLoginResponse.Size(m)
}
func (m *PassLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PassLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PassLoginResponse proto.InternalMessageInfo

func (m *PassLoginResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PassLoginResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{17}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

func init() {
	proto.RegisterEnum("srv.user.Enabled", Enabled_name, Enabled_value)
	proto.RegisterType((*Pagination)(nil), "srv.user.Pagination")
	proto.RegisterType((*Resource)(nil), "srv.user.Resource")
	proto.RegisterType((*List)(nil), "srv.user.List")
	proto.RegisterType((*ShowRequest)(nil), "srv.user.ShowRequest")
	proto.RegisterType((*ShowResponse)(nil), "srv.user.ShowResponse")
	proto.RegisterType((*MobileRequest)(nil), "srv.user.MobileRequest")
	proto.RegisterType((*MobileResponse)(nil), "srv.user.MobileResponse")
	proto.RegisterType((*MobileRegisterRequest)(nil), "srv.user.MobileRegisterRequest")
	proto.RegisterType((*MobileRegisterResponse)(nil), "srv.user.MobileRegisterResponse")
	proto.RegisterType((*ModifyPassRequest)(nil), "srv.user.ModifyPassRequest")
	proto.RegisterType((*ModifyPassResponse)(nil), "srv.user.ModifyPassResponse")
	proto.RegisterType((*ModifyMobileRequest)(nil), "srv.user.ModifyMobileRequest")
	proto.RegisterType((*ModifyMobileResponse)(nil), "srv.user.ModifyMobileResponse")
	proto.RegisterType((*ResetPassRequest)(nil), "srv.user.ResetPassRequest")
	proto.RegisterType((*ResetPassResponse)(nil), "srv.user.ResetPassResponse")
	proto.RegisterType((*PassLoginRequest)(nil), "srv.user.PassLoginRequest")
	proto.RegisterType((*PassLoginResponse)(nil), "srv.user.PassLoginResponse")
	proto.RegisterType((*Message)(nil), "srv.user.Message")
}

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor_9b283a848145d6b7) }

var fileDescriptor_9b283a848145d6b7 = []byte{
	// 820 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xcd, 0x6e, 0xeb, 0x44,
	0x14, 0x8e, 0x7f, 0xf2, 0xe3, 0x93, 0xde, 0x28, 0x19, 0xda, 0x32, 0x72, 0x7b, 0xb9, 0x91, 0x17,
	0x10, 0x81, 0x70, 0x50, 0x90, 0x2e, 0x77, 0x03, 0x82, 0x05, 0x20, 0x50, 0x03, 0x95, 0xa1, 0x0b,
	0x60, 0x35, 0x89, 0xa7, 0xa9, 0x85, 0xe3, 0x09, 0x1e, 0x87, 0x52, 0x9e, 0x83, 0x0d, 0x0f, 0xc3,
	0xbb, 0xa1, 0x99, 0xf1, 0xd8, 0x63, 0xb7, 0x4d, 0x74, 0x37, 0xd1, 0x9c, 0x9f, 0xf9, 0xce, 0x39,
	0xdf, 0x7c, 0xc7, 0x81, 0xb3, 0x5d, 0xce, 0x0a, 0x36, 0xdf, 0x73, 0x9a, 0xcb, 0x9f, 0x50, 0xda,
	0x68, 0xc0, 0xf3, 0x3f, 0x43, 0x61, 0xfb, 0xaf, 0x36, 0x8c, 0x6d, 0x52, 0x3a, 0x97, 0xfe, 0xd5,
	0xfe, 0x76, 0x5e, 0x24, 0x5b, 0xca, 0x0b, 0xb2, 0xdd, 0xa9, 0xd4, 0xe0, 0x1f, 0x0b, 0xe0, 0x9a,
	0x6c, 0x92, 0x8c, 0x14, 0x09, 0xcb, 0xd0, 0x29, 0x74, 0x0b, 0x56, 0x90, 0x14, 0x5b, 0x53, 0x6b,
	0xd6, 0x8d, 0x94, 0x81, 0x10, 0xb8, 0x3b, 0xb2, 0xa1, 0xd8, 0x96, 0x4e, 0x79, 0x16, 0x3e, 0x9e,
	0xfc, 0x4d, 0xb1, 0xa3, 0x7c, 0xe2, 0x8c, 0x2e, 0xc1, 0x5b, 0xb3, 0x2c, 0x4e, 0x04, 0x14, 0x76,
	0xa7, 0xce, 0xcc, 0x8b, 0x6a, 0x87, 0xc0, 0x66, 0x79, 0x4c, 0x73, 0xdc, 0x95, 0x11, 0x65, 0x08,
	0xef, 0x26, 0x67, 0xfb, 0x1d, 0xee, 0x29, 0xaf, 0x34, 0x82, 0x7f, 0x1d, 0x18, 0x44, 0x94, 0xb3,
	0x7d, 0xbe, 0xa6, 0xe8, 0x0d, 0x78, 0xeb, 0x9c, 0x92, 0x82, 0xc6, 0x5f, 0x15, 0xb2, 0xb1, 0xe1,
	0xc2, 0x0f, 0xd5, 0x60, 0xa1, 0x1e, 0x2c, 0xfc, 0x59, 0x0f, 0x16, 0xd5, 0xc9, 0xe2, 0xe6, 0x7e,
	0x17, 0x97, 0x37, 0xed, 0xe3, 0x37, 0xab, 0x64, 0x34, 0x02, 0x3b, 0x89, 0xcb, 0xe1, 0xec, 0x24,
	0x16, 0xe3, 0x66, 0x64, 0x4b, 0xb1, 0x3b, 0xb5, 0x66, 0x5e, 0x24, 0xcf, 0xc8, 0x87, 0x41, 0x96,
	0xac, 0x7f, 0x97, 0xfe, 0xae, 0xf4, 0x57, 0xb6, 0x88, 0xe5, 0x94, 0xa4, 0x32, 0xd6, 0x53, 0x31,
	0x6d, 0xa3, 0x73, 0xe8, 0x6d, 0xd9, 0x2a, 0x49, 0x29, 0xee, 0xcb, 0x48, 0x69, 0x09, 0x2a, 0xe8,
	0x96, 0x24, 0x29, 0x1e, 0x48, 0xb7, 0x32, 0x44, 0xe5, 0x35, 0x8b, 0x29, 0xf6, 0x54, 0x65, 0x71,
	0x16, 0x08, 0x8a, 0x1b, 0x0c, 0x0a, 0xa1, 0x64, 0xea, 0x35, 0x0c, 0x56, 0x49, 0x5e, 0xdc, 0xc5,
	0xe4, 0x01, 0x0f, 0x8f, 0x8e, 0x5b, 0xe5, 0xa2, 0x8f, 0xa0, 0x4f, 0x33, 0xb2, 0x4a, 0x69, 0x8c,
	0x4f, 0xa6, 0xd6, 0x6c, 0xb4, 0x98, 0x84, 0x5a, 0x42, 0xe1, 0xd7, 0x2a, 0x10, 0xe9, 0x8c, 0x20,
	0x04, 0xf7, 0x2a, 0xe1, 0x05, 0x7a, 0x1f, 0xdc, 0x98, 0x14, 0x04, 0x5b, 0x53, 0x67, 0x36, 0x5c,
	0xa0, 0xfa, 0x86, 0x7e, 0xb8, 0x48, 0xc6, 0x83, 0x97, 0x30, 0xfc, 0xe9, 0x8e, 0xdd, 0x47, 0xf4,
	0x8f, 0x3d, 0xe5, 0x9a, 0x59, 0x4b, 0x33, 0x1b, 0xbc, 0x86, 0x13, 0x15, 0xe6, 0x3b, 0x96, 0x71,
	0x6a, 0xc0, 0x5a, 0x07, 0x61, 0x3f, 0x80, 0x17, 0x4b, 0xc9, 0x9b, 0x06, 0xae, 0x69, 0xb5, 0x4c,
	0x5a, 0x83, 0x37, 0x30, 0xd2, 0x89, 0x6f, 0x59, 0xe2, 0x1e, 0xce, 0xf4, 0xcd, 0x4d, 0xc2, 0x0b,
	0x9a, 0xeb, 0x52, 0x5a, 0x0d, 0x96, 0xa1, 0x86, 0xba, 0xbc, 0xdd, 0x78, 0x55, 0x1f, 0x06, 0x3b,
	0xc2, 0xf9, 0x3d, 0xcb, 0x95, 0x9e, 0xbc, 0xa8, 0xb2, 0x8d, 0x77, 0x74, 0xcd, 0x77, 0x0c, 0x66,
	0x70, 0xde, 0x2e, 0x5c, 0xb6, 0xde, 0x66, 0x8f, 0xc0, 0x64, 0xc9, 0xe2, 0xe4, 0xf6, 0xe1, 0x9a,
	0x70, 0xfe, 0x0c, 0xc5, 0x68, 0x0a, 0x43, 0x96, 0xc6, 0xd7, 0xba, 0x0b, 0xd5, 0x9f, 0xe9, 0x3a,
	0xd4, 0x64, 0x10, 0x02, 0x32, 0x4b, 0x94, 0x8d, 0x60, 0xe8, 0xf3, 0xfd, 0x7a, 0x4d, 0x39, 0x97,
	0x85, 0x06, 0x91, 0x36, 0x83, 0xdf, 0xe0, 0x1d, 0x95, 0xdf, 0x7c, 0x9e, 0x76, 0x53, 0x97, 0xe0,
	0xb1, 0x34, 0x5e, 0x9a, 0x94, 0xd5, 0x0e, 0x83, 0x4d, 0xa7, 0xf1, 0x98, 0x9f, 0xc0, 0x69, 0x13,
	0xfc, 0x68, 0x3b, 0x5f, 0xc0, 0x38, 0xa2, 0x9c, 0x16, 0x87, 0x08, 0x32, 0xc7, 0xb7, 0x5b, 0xe3,
	0x7f, 0x0c, 0x13, 0xe3, 0xfe, 0xd1, 0x72, 0xbf, 0xc2, 0x58, 0x64, 0x5e, 0xb1, 0x4d, 0x92, 0x19,
	0x72, 0x11, 0xf2, 0xd2, 0x72, 0x11, 0xe7, 0x43, 0x25, 0x0d, 0x59, 0x38, 0x0d, 0x59, 0x7c, 0x0e,
	0x13, 0x03, 0xfb, 0x69, 0x45, 0x98, 0xad, 0xd9, 0xcd, 0xd6, 0x2e, 0xa0, 0xbf, 0xa4, 0x9c, 0x8b,
	0xaf, 0xf7, 0x18, 0x1c, 0x4e, 0x1e, 0xca, 0x86, 0xc4, 0xf1, 0x43, 0x1f, 0xfa, 0xe5, 0xa6, 0xa3,
	0x1e, 0xd8, 0x3f, 0xb0, 0x71, 0x07, 0xf5, 0xc1, 0xf9, 0x85, 0xf2, 0xb1, 0xb5, 0xf8, 0xcf, 0x05,
	0xf7, 0x46, 0x34, 0x3d, 0x87, 0xee, 0x77, 0x59, 0x4c, 0xff, 0x42, 0xa7, 0xf5, 0xce, 0xd4, 0xff,
	0x1e, 0xfe, 0xa8, 0xf6, 0x8a, 0x2f, 0x44, 0xd0, 0x41, 0x9f, 0x81, 0x2b, 0x96, 0x1b, 0x9d, 0xd5,
	0x11, 0xe3, 0x5b, 0xe0, 0x9f, 0xb7, 0xdd, 0x6a, 0xa6, 0xa0, 0x83, 0xbe, 0x04, 0xef, 0x5b, 0x5a,
	0x94, 0x62, 0x78, 0xb7, 0x4e, 0x6b, 0x68, 0xca, 0xc7, 0x8f, 0x03, 0x15, 0xc2, 0x4d, 0xbd, 0xf6,
	0x6a, 0x87, 0xd0, 0xab, 0xc7, 0xd9, 0x8d, 0xb5, 0xf6, 0xa7, 0xcf, 0x27, 0x54, 0xb0, 0x4b, 0x01,
	0xab, 0xb7, 0x41, 0xbe, 0xd6, 0x85, 0x79, 0xab, 0xb5, 0x8a, 0xfe, 0xe5, 0xd3, 0xc1, 0x0a, 0xee,
	0x7b, 0x78, 0x51, 0xa9, 0x4b, 0x6d, 0x62, 0xe3, 0x6b, 0xd4, 0x90, 0xad, 0x7f, 0xf1, 0x64, 0xac,
	0xc2, 0xfa, 0x11, 0x4e, 0xcc, 0xdd, 0x40, 0x2f, 0xdb, 0xb5, 0x9b, 0xe4, 0xbd, 0xf7, 0x5c, 0xb8,
	0x02, 0xfc, 0x06, 0xbc, 0x4a, 0x6f, 0x66, 0x63, 0x6d, 0x81, 0x9b, 0x8d, 0x3d, 0x12, 0x68, 0xd0,
	0x59, 0xf5, 0xe4, 0x9f, 0xcf, 0xa7, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0x86, 0xbd, 0xdc, 0x09,
	0xaf, 0x08, 0x00, 0x00,
}
