// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package srv_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SortType int32

const (
	SortType_ASC  SortType = 0
	SortType_DESC SortType = 2
)

var SortType_name = map[int32]string{
	0: "ASC",
	2: "DESC",
}

var SortType_value = map[string]int32{
	"ASC":  0,
	"DESC": 2,
}

func (x SortType) String() string {
	return proto.EnumName(SortType_name, int32(x))
}

func (SortType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

type Enabled int32

const (
	Enabled_No  Enabled = 0
	Enabled_Yes Enabled = 1
)

var Enabled_name = map[int32]string{
	0: "No",
	1: "Yes",
}

var Enabled_value = map[string]int32{
	"No":  0,
	"Yes": 1,
}

func (x Enabled) String() string {
	return proto.EnumName(Enabled_name, int32(x))
}

func (Enabled) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{1}
}

type SearchPageRequest struct {
	Total                int32                        `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Page                 int32                        `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32                        `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Condition            *SearchPageRequest_Condition `protobuf:"bytes,4,opt,name=condition,proto3" json:"condition,omitempty"`
	Order                []*Order                     `protobuf:"bytes,5,rep,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *SearchPageRequest) Reset()         { *m = SearchPageRequest{} }
func (m *SearchPageRequest) String() string { return proto.CompactTextString(m) }
func (*SearchPageRequest) ProtoMessage()    {}
func (*SearchPageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

func (m *SearchPageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchPageRequest.Unmarshal(m, b)
}
func (m *SearchPageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchPageRequest.Marshal(b, m, deterministic)
}
func (m *SearchPageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchPageRequest.Merge(m, src)
}
func (m *SearchPageRequest) XXX_Size() int {
	return xxx_messageInfo_SearchPageRequest.Size(m)
}
func (m *SearchPageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchPageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchPageRequest proto.InternalMessageInfo

func (m *SearchPageRequest) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *SearchPageRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *SearchPageRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *SearchPageRequest) GetCondition() *SearchPageRequest_Condition {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (m *SearchPageRequest) GetOrder() []*Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type SearchPageRequest_Condition struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	CreatedAt            *Between `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchPageRequest_Condition) Reset()         { *m = SearchPageRequest_Condition{} }
func (m *SearchPageRequest_Condition) String() string { return proto.CompactTextString(m) }
func (*SearchPageRequest_Condition) ProtoMessage()    {}
func (*SearchPageRequest_Condition) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0, 0}
}

func (m *SearchPageRequest_Condition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchPageRequest_Condition.Unmarshal(m, b)
}
func (m *SearchPageRequest_Condition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchPageRequest_Condition.Marshal(b, m, deterministic)
}
func (m *SearchPageRequest_Condition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchPageRequest_Condition.Merge(m, src)
}
func (m *SearchPageRequest_Condition) XXX_Size() int {
	return xxx_messageInfo_SearchPageRequest_Condition.Size(m)
}
func (m *SearchPageRequest_Condition) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchPageRequest_Condition.DiscardUnknown(m)
}

var xxx_messageInfo_SearchPageRequest_Condition proto.InternalMessageInfo

func (m *SearchPageRequest_Condition) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *SearchPageRequest_Condition) GetCreatedAt() *Between {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type Between struct {
	Start                *timestamp.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End                  *timestamp.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Between) Reset()         { *m = Between{} }
func (m *Between) String() string { return proto.CompactTextString(m) }
func (*Between) ProtoMessage()    {}
func (*Between) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{1}
}

func (m *Between) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Between.Unmarshal(m, b)
}
func (m *Between) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Between.Marshal(b, m, deterministic)
}
func (m *Between) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Between.Merge(m, src)
}
func (m *Between) XXX_Size() int {
	return xxx_messageInfo_Between.Size(m)
}
func (m *Between) XXX_DiscardUnknown() {
	xxx_messageInfo_Between.DiscardUnknown(m)
}

var xxx_messageInfo_Between proto.InternalMessageInfo

func (m *Between) GetStart() *timestamp.Timestamp {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *Between) GetEnd() *timestamp.Timestamp {
	if m != nil {
		return m.End
	}
	return nil
}

type Order struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val                  SortType `protobuf:"varint,2,opt,name=val,proto3,enum=srv.user.SortType" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{2}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Order) GetVal() SortType {
	if m != nil {
		return m.Val
	}
	return SortType_ASC
}

type Pagination struct {
	Total                int32    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Condition            []string `protobuf:"bytes,4,rep,name=condition,proto3" json:"condition,omitempty"`
	Order                []string `protobuf:"bytes,5,rep,name=order,proto3" json:"order,omitempty"`
	Group                []string `protobuf:"bytes,6,rep,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pagination) Reset()         { *m = Pagination{} }
func (m *Pagination) String() string { return proto.CompactTextString(m) }
func (*Pagination) ProtoMessage()    {}
func (*Pagination) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{3}
}

func (m *Pagination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pagination.Unmarshal(m, b)
}
func (m *Pagination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pagination.Marshal(b, m, deterministic)
}
func (m *Pagination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pagination.Merge(m, src)
}
func (m *Pagination) XXX_Size() int {
	return xxx_messageInfo_Pagination.Size(m)
}
func (m *Pagination) XXX_DiscardUnknown() {
	xxx_messageInfo_Pagination.DiscardUnknown(m)
}

var xxx_messageInfo_Pagination proto.InternalMessageInfo

func (m *Pagination) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Pagination) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Pagination) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Pagination) GetCondition() []string {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (m *Pagination) GetOrder() []string {
	if m != nil {
		return m.Order
	}
	return nil
}

func (m *Pagination) GetGroup() []string {
	if m != nil {
		return m.Group
	}
	return nil
}

type Resource struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Nickname             string               `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Realname             string               `protobuf:"bytes,3,opt,name=realname,proto3" json:"realname,omitempty"`
	Mobile               string               `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Email                string               `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Code                 string               `protobuf:"bytes,6,opt,name=code,proto3" json:"code,omitempty"`
	Source               string               `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	Birthday             *timestamp.Timestamp `protobuf:"bytes,8,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Enabled              Enabled              `protobuf:"varint,9,opt,name=enabled,proto3,enum=srv.user.Enabled" json:"enabled,omitempty"`
	Id                   int32                `protobuf:"varint,10,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,11,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,12,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Resource) Reset()         { *m = Resource{} }
func (m *Resource) String() string { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()    {}
func (*Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{4}
}

func (m *Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resource.Unmarshal(m, b)
}
func (m *Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resource.Marshal(b, m, deterministic)
}
func (m *Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resource.Merge(m, src)
}
func (m *Resource) XXX_Size() int {
	return xxx_messageInfo_Resource.Size(m)
}
func (m *Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_Resource proto.InternalMessageInfo

func (m *Resource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Resource) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *Resource) GetRealname() string {
	if m != nil {
		return m.Realname
	}
	return ""
}

func (m *Resource) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *Resource) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Resource) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Resource) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Resource) GetBirthday() *timestamp.Timestamp {
	if m != nil {
		return m.Birthday
	}
	return nil
}

func (m *Resource) GetEnabled() Enabled {
	if m != nil {
		return m.Enabled
	}
	return Enabled_No
}

func (m *Resource) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Resource) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Resource) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type List struct {
	Data                 []*Resource `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *List) Reset()         { *m = List{} }
func (m *List) String() string { return proto.CompactTextString(m) }
func (*List) ProtoMessage()    {}
func (*List) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{5}
}

func (m *List) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_List.Unmarshal(m, b)
}
func (m *List) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_List.Marshal(b, m, deterministic)
}
func (m *List) XXX_Merge(src proto.Message) {
	xxx_messageInfo_List.Merge(m, src)
}
func (m *List) XXX_Size() int {
	return xxx_messageInfo_List.Size(m)
}
func (m *List) XXX_DiscardUnknown() {
	xxx_messageInfo_List.DiscardUnknown(m)
}

var xxx_messageInfo_List proto.InternalMessageInfo

func (m *List) GetData() []*Resource {
	if m != nil {
		return m.Data
	}
	return nil
}

type ShowRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowRequest) Reset()         { *m = ShowRequest{} }
func (m *ShowRequest) String() string { return proto.CompactTextString(m) }
func (*ShowRequest) ProtoMessage()    {}
func (*ShowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{6}
}

func (m *ShowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowRequest.Unmarshal(m, b)
}
func (m *ShowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowRequest.Marshal(b, m, deterministic)
}
func (m *ShowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowRequest.Merge(m, src)
}
func (m *ShowRequest) XXX_Size() int {
	return xxx_messageInfo_ShowRequest.Size(m)
}
func (m *ShowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShowRequest proto.InternalMessageInfo

func (m *ShowRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ShowResponse struct {
	Data                 *Resource `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ShowResponse) Reset()         { *m = ShowResponse{} }
func (m *ShowResponse) String() string { return proto.CompactTextString(m) }
func (*ShowResponse) ProtoMessage()    {}
func (*ShowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{7}
}

func (m *ShowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowResponse.Unmarshal(m, b)
}
func (m *ShowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowResponse.Marshal(b, m, deterministic)
}
func (m *ShowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowResponse.Merge(m, src)
}
func (m *ShowResponse) XXX_Size() int {
	return xxx_messageInfo_ShowResponse.Size(m)
}
func (m *ShowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShowResponse proto.InternalMessageInfo

func (m *ShowResponse) GetData() *Resource {
	if m != nil {
		return m.Data
	}
	return nil
}

type MobileRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MobileRequest) Reset()         { *m = MobileRequest{} }
func (m *MobileRequest) String() string { return proto.CompactTextString(m) }
func (*MobileRequest) ProtoMessage()    {}
func (*MobileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{8}
}

func (m *MobileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MobileRequest.Unmarshal(m, b)
}
func (m *MobileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MobileRequest.Marshal(b, m, deterministic)
}
func (m *MobileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MobileRequest.Merge(m, src)
}
func (m *MobileRequest) XXX_Size() int {
	return xxx_messageInfo_MobileRequest.Size(m)
}
func (m *MobileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MobileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MobileRequest proto.InternalMessageInfo

func (m *MobileRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

type MobileResponse struct {
	Data                 *Resource `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MobileResponse) Reset()         { *m = MobileResponse{} }
func (m *MobileResponse) String() string { return proto.CompactTextString(m) }
func (*MobileResponse) ProtoMessage()    {}
func (*MobileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{9}
}

func (m *MobileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MobileResponse.Unmarshal(m, b)
}
func (m *MobileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MobileResponse.Marshal(b, m, deterministic)
}
func (m *MobileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MobileResponse.Merge(m, src)
}
func (m *MobileResponse) XXX_Size() int {
	return xxx_messageInfo_MobileResponse.Size(m)
}
func (m *MobileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MobileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MobileResponse proto.InternalMessageInfo

func (m *MobileResponse) GetData() *Resource {
	if m != nil {
		return m.Data
	}
	return nil
}

type ModifyPassRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OldPassword          string   `protobuf:"bytes,2,opt,name=oldPassword,proto3" json:"oldPassword,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyPassRequest) Reset()         { *m = ModifyPassRequest{} }
func (m *ModifyPassRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyPassRequest) ProtoMessage()    {}
func (*ModifyPassRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{10}
}

func (m *ModifyPassRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyPassRequest.Unmarshal(m, b)
}
func (m *ModifyPassRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyPassRequest.Marshal(b, m, deterministic)
}
func (m *ModifyPassRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyPassRequest.Merge(m, src)
}
func (m *ModifyPassRequest) XXX_Size() int {
	return xxx_messageInfo_ModifyPassRequest.Size(m)
}
func (m *ModifyPassRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyPassRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyPassRequest proto.InternalMessageInfo

func (m *ModifyPassRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ModifyPassRequest) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

func (m *ModifyPassRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ModifyPassResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyPassResponse) Reset()         { *m = ModifyPassResponse{} }
func (m *ModifyPassResponse) String() string { return proto.CompactTextString(m) }
func (*ModifyPassResponse) ProtoMessage()    {}
func (*ModifyPassResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{11}
}

func (m *ModifyPassResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyPassResponse.Unmarshal(m, b)
}
func (m *ModifyPassResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyPassResponse.Marshal(b, m, deterministic)
}
func (m *ModifyPassResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyPassResponse.Merge(m, src)
}
func (m *ModifyPassResponse) XXX_Size() int {
	return xxx_messageInfo_ModifyPassResponse.Size(m)
}
func (m *ModifyPassResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyPassResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyPassResponse proto.InternalMessageInfo

func (m *ModifyPassResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ModifyMobileRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OldMobile            string   `protobuf:"bytes,2,opt,name=oldMobile,proto3" json:"oldMobile,omitempty"`
	Mobile               string   `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyMobileRequest) Reset()         { *m = ModifyMobileRequest{} }
func (m *ModifyMobileRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyMobileRequest) ProtoMessage()    {}
func (*ModifyMobileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{12}
}

func (m *ModifyMobileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyMobileRequest.Unmarshal(m, b)
}
func (m *ModifyMobileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyMobileRequest.Marshal(b, m, deterministic)
}
func (m *ModifyMobileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyMobileRequest.Merge(m, src)
}
func (m *ModifyMobileRequest) XXX_Size() int {
	return xxx_messageInfo_ModifyMobileRequest.Size(m)
}
func (m *ModifyMobileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyMobileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyMobileRequest proto.InternalMessageInfo

func (m *ModifyMobileRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ModifyMobileRequest) GetOldMobile() string {
	if m != nil {
		return m.OldMobile
	}
	return ""
}

func (m *ModifyMobileRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

type ModifyMobileResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyMobileResponse) Reset()         { *m = ModifyMobileResponse{} }
func (m *ModifyMobileResponse) String() string { return proto.CompactTextString(m) }
func (*ModifyMobileResponse) ProtoMessage()    {}
func (*ModifyMobileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{13}
}

func (m *ModifyMobileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyMobileResponse.Unmarshal(m, b)
}
func (m *ModifyMobileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyMobileResponse.Marshal(b, m, deterministic)
}
func (m *ModifyMobileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyMobileResponse.Merge(m, src)
}
func (m *ModifyMobileResponse) XXX_Size() int {
	return xxx_messageInfo_ModifyMobileResponse.Size(m)
}
func (m *ModifyMobileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyMobileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyMobileResponse proto.InternalMessageInfo

func (m *ModifyMobileResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ResetPassRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPassRequest) Reset()         { *m = ResetPassRequest{} }
func (m *ResetPassRequest) String() string { return proto.CompactTextString(m) }
func (*ResetPassRequest) ProtoMessage()    {}
func (*ResetPassRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{14}
}

func (m *ResetPassRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPassRequest.Unmarshal(m, b)
}
func (m *ResetPassRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPassRequest.Marshal(b, m, deterministic)
}
func (m *ResetPassRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPassRequest.Merge(m, src)
}
func (m *ResetPassRequest) XXX_Size() int {
	return xxx_messageInfo_ResetPassRequest.Size(m)
}
func (m *ResetPassRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPassRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPassRequest proto.InternalMessageInfo

func (m *ResetPassRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ResetPassRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ResetPassResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPassResponse) Reset()         { *m = ResetPassResponse{} }
func (m *ResetPassResponse) String() string { return proto.CompactTextString(m) }
func (*ResetPassResponse) ProtoMessage()    {}
func (*ResetPassResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{15}
}

func (m *ResetPassResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPassResponse.Unmarshal(m, b)
}
func (m *ResetPassResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPassResponse.Marshal(b, m, deterministic)
}
func (m *ResetPassResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPassResponse.Merge(m, src)
}
func (m *ResetPassResponse) XXX_Size() int {
	return xxx_messageInfo_ResetPassResponse.Size(m)
}
func (m *ResetPassResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPassResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPassResponse proto.InternalMessageInfo

func (m *ResetPassResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type PassLoginRequest struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Source               string   `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PassLoginRequest) Reset()         { *m = PassLoginRequest{} }
func (m *PassLoginRequest) String() string { return proto.CompactTextString(m) }
func (*PassLoginRequest) ProtoMessage()    {}
func (*PassLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{16}
}

func (m *PassLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PassLoginRequest.Unmarshal(m, b)
}
func (m *PassLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PassLoginRequest.Marshal(b, m, deterministic)
}
func (m *PassLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PassLoginRequest.Merge(m, src)
}
func (m *PassLoginRequest) XXX_Size() int {
	return xxx_messageInfo_PassLoginRequest.Size(m)
}
func (m *PassLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PassLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PassLoginRequest proto.InternalMessageInfo

func (m *PassLoginRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *PassLoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *PassLoginRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

type PassLoginResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PassLoginResponse) Reset()         { *m = PassLoginResponse{} }
func (m *PassLoginResponse) String() string { return proto.CompactTextString(m) }
func (*PassLoginResponse) ProtoMessage()    {}
func (*PassLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{17}
}

func (m *PassLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PassLoginResponse.Unmarshal(m, b)
}
func (m *PassLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PassLoginResponse.Marshal(b, m, deterministic)
}
func (m *PassLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PassLoginResponse.Merge(m, src)
}
func (m *PassLoginResponse) XXX_Size() int {
	return xxx_messageInfo_PassLoginResponse.Size(m)
}
func (m *PassLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PassLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PassLoginResponse proto.InternalMessageInfo

func (m *PassLoginResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PassLoginResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type MobileRegisterRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mobile               string   `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Source               string   `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MobileRegisterRequest) Reset()         { *m = MobileRegisterRequest{} }
func (m *MobileRegisterRequest) String() string { return proto.CompactTextString(m) }
func (*MobileRegisterRequest) ProtoMessage()    {}
func (*MobileRegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{18}
}

func (m *MobileRegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MobileRegisterRequest.Unmarshal(m, b)
}
func (m *MobileRegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MobileRegisterRequest.Marshal(b, m, deterministic)
}
func (m *MobileRegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MobileRegisterRequest.Merge(m, src)
}
func (m *MobileRegisterRequest) XXX_Size() int {
	return xxx_messageInfo_MobileRegisterRequest.Size(m)
}
func (m *MobileRegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MobileRegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MobileRegisterRequest proto.InternalMessageInfo

func (m *MobileRegisterRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MobileRegisterRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *MobileRegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *MobileRegisterRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

type MobileRegisterResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MobileRegisterResponse) Reset()         { *m = MobileRegisterResponse{} }
func (m *MobileRegisterResponse) String() string { return proto.CompactTextString(m) }
func (*MobileRegisterResponse) ProtoMessage()    {}
func (*MobileRegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{19}
}

func (m *MobileRegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MobileRegisterResponse.Unmarshal(m, b)
}
func (m *MobileRegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MobileRegisterResponse.Marshal(b, m, deterministic)
}
func (m *MobileRegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MobileRegisterResponse.Merge(m, src)
}
func (m *MobileRegisterResponse) XXX_Size() int {
	return xxx_messageInfo_MobileRegisterResponse.Size(m)
}
func (m *MobileRegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MobileRegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MobileRegisterResponse proto.InternalMessageInfo

func (m *MobileRegisterResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MobileRegisterResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type FindInIdRequest struct {
	Id                   []int32  `protobuf:"varint,1,rep,packed,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindInIdRequest) Reset()         { *m = FindInIdRequest{} }
func (m *FindInIdRequest) String() string { return proto.CompactTextString(m) }
func (*FindInIdRequest) ProtoMessage()    {}
func (*FindInIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{20}
}

func (m *FindInIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindInIdRequest.Unmarshal(m, b)
}
func (m *FindInIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindInIdRequest.Marshal(b, m, deterministic)
}
func (m *FindInIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindInIdRequest.Merge(m, src)
}
func (m *FindInIdRequest) XXX_Size() int {
	return xxx_messageInfo_FindInIdRequest.Size(m)
}
func (m *FindInIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindInIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindInIdRequest proto.InternalMessageInfo

func (m *FindInIdRequest) GetId() []int32 {
	if m != nil {
		return m.Id
	}
	return nil
}

type FindInMobileRequest struct {
	Mobile               []string `protobuf:"bytes,1,rep,name=mobile,proto3" json:"mobile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindInMobileRequest) Reset()         { *m = FindInMobileRequest{} }
func (m *FindInMobileRequest) String() string { return proto.CompactTextString(m) }
func (*FindInMobileRequest) ProtoMessage()    {}
func (*FindInMobileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{21}
}

func (m *FindInMobileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindInMobileRequest.Unmarshal(m, b)
}
func (m *FindInMobileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindInMobileRequest.Marshal(b, m, deterministic)
}
func (m *FindInMobileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindInMobileRequest.Merge(m, src)
}
func (m *FindInMobileRequest) XXX_Size() int {
	return xxx_messageInfo_FindInMobileRequest.Size(m)
}
func (m *FindInMobileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindInMobileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindInMobileRequest proto.InternalMessageInfo

func (m *FindInMobileRequest) GetMobile() []string {
	if m != nil {
		return m.Mobile
	}
	return nil
}

type FindLikeMobileRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindLikeMobileRequest) Reset()         { *m = FindLikeMobileRequest{} }
func (m *FindLikeMobileRequest) String() string { return proto.CompactTextString(m) }
func (*FindLikeMobileRequest) ProtoMessage()    {}
func (*FindLikeMobileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{22}
}

func (m *FindLikeMobileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindLikeMobileRequest.Unmarshal(m, b)
}
func (m *FindLikeMobileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindLikeMobileRequest.Marshal(b, m, deterministic)
}
func (m *FindLikeMobileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindLikeMobileRequest.Merge(m, src)
}
func (m *FindLikeMobileRequest) XXX_Size() int {
	return xxx_messageInfo_FindLikeMobileRequest.Size(m)
}
func (m *FindLikeMobileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindLikeMobileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindLikeMobileRequest proto.InternalMessageInfo

func (m *FindLikeMobileRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

type FindSourceRequest struct {
	Source               string   `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindSourceRequest) Reset()         { *m = FindSourceRequest{} }
func (m *FindSourceRequest) String() string { return proto.CompactTextString(m) }
func (*FindSourceRequest) ProtoMessage()    {}
func (*FindSourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{23}
}

func (m *FindSourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindSourceRequest.Unmarshal(m, b)
}
func (m *FindSourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindSourceRequest.Marshal(b, m, deterministic)
}
func (m *FindSourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindSourceRequest.Merge(m, src)
}
func (m *FindSourceRequest) XXX_Size() int {
	return xxx_messageInfo_FindSourceRequest.Size(m)
}
func (m *FindSourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindSourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindSourceRequest proto.InternalMessageInfo

func (m *FindSourceRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

type FindMobileRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindMobileRequest) Reset()         { *m = FindMobileRequest{} }
func (m *FindMobileRequest) String() string { return proto.CompactTextString(m) }
func (*FindMobileRequest) ProtoMessage()    {}
func (*FindMobileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{24}
}

func (m *FindMobileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindMobileRequest.Unmarshal(m, b)
}
func (m *FindMobileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindMobileRequest.Marshal(b, m, deterministic)
}
func (m *FindMobileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindMobileRequest.Merge(m, src)
}
func (m *FindMobileRequest) XXX_Size() int {
	return xxx_messageInfo_FindMobileRequest.Size(m)
}
func (m *FindMobileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindMobileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindMobileRequest proto.InternalMessageInfo

func (m *FindMobileRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

type SourceTypeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SourceTypeRequest) Reset()         { *m = SourceTypeRequest{} }
func (m *SourceTypeRequest) String() string { return proto.CompactTextString(m) }
func (*SourceTypeRequest) ProtoMessage()    {}
func (*SourceTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{25}
}

func (m *SourceTypeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SourceTypeRequest.Unmarshal(m, b)
}
func (m *SourceTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SourceTypeRequest.Marshal(b, m, deterministic)
}
func (m *SourceTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceTypeRequest.Merge(m, src)
}
func (m *SourceTypeRequest) XXX_Size() int {
	return xxx_messageInfo_SourceTypeRequest.Size(m)
}
func (m *SourceTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SourceTypeRequest proto.InternalMessageInfo

type SourceTypeResponse struct {
	Type                 []string `protobuf:"bytes,1,rep,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SourceTypeResponse) Reset()         { *m = SourceTypeResponse{} }
func (m *SourceTypeResponse) String() string { return proto.CompactTextString(m) }
func (*SourceTypeResponse) ProtoMessage()    {}
func (*SourceTypeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{26}
}

func (m *SourceTypeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SourceTypeResponse.Unmarshal(m, b)
}
func (m *SourceTypeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SourceTypeResponse.Marshal(b, m, deterministic)
}
func (m *SourceTypeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceTypeResponse.Merge(m, src)
}
func (m *SourceTypeResponse) XXX_Size() int {
	return xxx_messageInfo_SourceTypeResponse.Size(m)
}
func (m *SourceTypeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceTypeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SourceTypeResponse proto.InternalMessageInfo

func (m *SourceTypeResponse) GetType() []string {
	if m != nil {
		return m.Type
	}
	return nil
}

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{27}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

func init() {
	proto.RegisterEnum("srv.user.SortType", SortType_name, SortType_value)
	proto.RegisterEnum("srv.user.Enabled", Enabled_name, Enabled_value)
	proto.RegisterType((*SearchPageRequest)(nil), "srv.user.SearchPageRequest")
	proto.RegisterType((*SearchPageRequest_Condition)(nil), "srv.user.SearchPageRequest.Condition")
	proto.RegisterType((*Between)(nil), "srv.user.Between")
	proto.RegisterType((*Order)(nil), "srv.user.Order")
	proto.RegisterType((*Pagination)(nil), "srv.user.Pagination")
	proto.RegisterType((*Resource)(nil), "srv.user.Resource")
	proto.RegisterType((*List)(nil), "srv.user.List")
	proto.RegisterType((*ShowRequest)(nil), "srv.user.ShowRequest")
	proto.RegisterType((*ShowResponse)(nil), "srv.user.ShowResponse")
	proto.RegisterType((*MobileRequest)(nil), "srv.user.MobileRequest")
	proto.RegisterType((*MobileResponse)(nil), "srv.user.MobileResponse")
	proto.RegisterType((*ModifyPassRequest)(nil), "srv.user.ModifyPassRequest")
	proto.RegisterType((*ModifyPassResponse)(nil), "srv.user.ModifyPassResponse")
	proto.RegisterType((*ModifyMobileRequest)(nil), "srv.user.ModifyMobileRequest")
	proto.RegisterType((*ModifyMobileResponse)(nil), "srv.user.ModifyMobileResponse")
	proto.RegisterType((*ResetPassRequest)(nil), "srv.user.ResetPassRequest")
	proto.RegisterType((*ResetPassResponse)(nil), "srv.user.ResetPassResponse")
	proto.RegisterType((*PassLoginRequest)(nil), "srv.user.PassLoginRequest")
	proto.RegisterType((*PassLoginResponse)(nil), "srv.user.PassLoginResponse")
	proto.RegisterType((*MobileRegisterRequest)(nil), "srv.user.MobileRegisterRequest")
	proto.RegisterType((*MobileRegisterResponse)(nil), "srv.user.MobileRegisterResponse")
	proto.RegisterType((*FindInIdRequest)(nil), "srv.user.FindInIdRequest")
	proto.RegisterType((*FindInMobileRequest)(nil), "srv.user.FindInMobileRequest")
	proto.RegisterType((*FindLikeMobileRequest)(nil), "srv.user.FindLikeMobileRequest")
	proto.RegisterType((*FindSourceRequest)(nil), "srv.user.FindSourceRequest")
	proto.RegisterType((*FindMobileRequest)(nil), "srv.user.FindMobileRequest")
	proto.RegisterType((*SourceTypeRequest)(nil), "srv.user.SourceTypeRequest")
	proto.RegisterType((*SourceTypeResponse)(nil), "srv.user.SourceTypeResponse")
	proto.RegisterType((*Message)(nil), "srv.user.Message")
}

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor_9b283a848145d6b7) }

var fileDescriptor_9b283a848145d6b7 = []byte{
	// 1156 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0x51, 0x6f, 0xdb, 0x36,
	0x10, 0x8e, 0x2d, 0x39, 0xb6, 0xcf, 0xa9, 0x6b, 0xb3, 0x49, 0xa6, 0x29, 0xc9, 0x92, 0x09, 0xeb,
	0x16, 0xb4, 0xab, 0x5d, 0x78, 0x40, 0x57, 0x60, 0xd8, 0xba, 0x36, 0x4d, 0x8b, 0x0c, 0xc9, 0x1a,
	0x28, 0xe9, 0xc3, 0xb6, 0x27, 0xc6, 0x62, 0x1d, 0x21, 0x8e, 0xe8, 0x89, 0x74, 0x33, 0xef, 0x6f,
	0x6c, 0x2f, 0x03, 0xf6, 0x63, 0x07, 0x92, 0xa2, 0x44, 0x49, 0x8e, 0xdd, 0x62, 0x2f, 0x81, 0x78,
	0xf7, 0xf1, 0xbb, 0xe3, 0xdd, 0xf1, 0x63, 0x0c, 0x1b, 0x93, 0x98, 0x72, 0xda, 0x9f, 0x32, 0x12,
	0xcb, 0x3f, 0x3d, 0xb9, 0x46, 0x0d, 0x16, 0xbf, 0xef, 0x89, 0xb5, 0xbb, 0x3b, 0xa2, 0x74, 0x34,
	0x26, 0x7d, 0x69, 0xbf, 0x98, 0xbe, 0xeb, 0xf3, 0xf0, 0x9a, 0x30, 0x8e, 0xaf, 0x27, 0x0a, 0xea,
	0xfd, 0x55, 0x85, 0xee, 0x19, 0xc1, 0xf1, 0xf0, 0xf2, 0x14, 0x8f, 0x88, 0x4f, 0x7e, 0x9f, 0x12,
	0xc6, 0xd1, 0x3a, 0xd4, 0x38, 0xe5, 0x78, 0xec, 0x54, 0xf6, 0x2a, 0xfb, 0x35, 0x5f, 0x2d, 0x10,
	0x02, 0x7b, 0x82, 0x47, 0xc4, 0xa9, 0x4a, 0xa3, 0xfc, 0x16, 0x36, 0x16, 0xfe, 0x49, 0x1c, 0x4b,
	0xd9, 0xc4, 0x37, 0x3a, 0x80, 0xe6, 0x90, 0x46, 0x41, 0xc8, 0x43, 0x1a, 0x39, 0xf6, 0x5e, 0x65,
	0xbf, 0x35, 0xb8, 0xdf, 0xd3, 0x29, 0xf5, 0x4a, 0xd1, 0x7a, 0x07, 0x1a, 0xec, 0x67, 0xfb, 0xd0,
	0x7d, 0xa8, 0xd1, 0x38, 0x20, 0xb1, 0x53, 0xdb, 0xb3, 0xf6, 0x5b, 0x83, 0xbb, 0x19, 0xc1, 0x1b,
	0x61, 0xf6, 0x95, 0xd7, 0x3d, 0x87, 0x66, 0xba, 0x1d, 0x6d, 0xc2, 0xea, 0x35, 0xbd, 0x08, 0xc7,
	0x44, 0xe6, 0xdd, 0xf4, 0x93, 0x15, 0xea, 0x43, 0x73, 0x18, 0x13, 0xcc, 0x49, 0xf0, 0x9c, 0xcb,
	0xec, 0x5b, 0x83, 0x6e, 0xc6, 0xf7, 0x82, 0xf0, 0x1b, 0x42, 0x44, 0x70, 0x8d, 0xf1, 0x42, 0xa8,
	0x27, 0x56, 0xf4, 0x18, 0x6a, 0x8c, 0xe3, 0x98, 0x4b, 0xca, 0xd6, 0xc0, 0xed, 0xa9, 0x8a, 0xf6,
	0x74, 0x45, 0x7b, 0xe7, 0xba, 0xa2, 0xbe, 0x02, 0xa2, 0xaf, 0xc1, 0x22, 0x51, 0x90, 0xc4, 0x59,
	0x84, 0x17, 0x30, 0xef, 0x19, 0xd4, 0xe4, 0x81, 0x50, 0x07, 0xac, 0x2b, 0x32, 0x4b, 0x32, 0x17,
	0x9f, 0xe8, 0x0b, 0xb0, 0xde, 0xe3, 0xb1, 0x24, 0x6a, 0x0f, 0x90, 0x51, 0x41, 0x1a, 0xf3, 0xf3,
	0xd9, 0x84, 0xf8, 0xc2, 0xed, 0xfd, 0x5d, 0x01, 0x38, 0xc5, 0xa3, 0x30, 0xc2, 0xb2, 0x06, 0xff,
	0xaf, 0x75, 0xdb, 0xf9, 0xd6, 0x59, 0xfb, 0x4d, 0xb3, 0x27, 0xeb, 0x66, 0x4f, 0x9a, 0x49, 0x0b,
	0x84, 0x75, 0x14, 0xd3, 0xe9, 0xc4, 0x59, 0x55, 0x56, 0xb9, 0xf0, 0xfe, 0xb1, 0xa0, 0xe1, 0x13,
	0x46, 0xa7, 0xf1, 0x50, 0x86, 0x8a, 0xf0, 0xb5, 0x6e, 0x8b, 0xfc, 0x46, 0x2e, 0x34, 0xa2, 0x70,
	0x78, 0x25, 0xed, 0x55, 0x69, 0x4f, 0xd7, 0xc2, 0x17, 0x13, 0x3c, 0x96, 0x3e, 0x4b, 0xf9, 0xf4,
	0xda, 0x68, 0xb2, 0x9d, 0x6b, 0xf2, 0x3a, 0xd4, 0xc8, 0x35, 0x0e, 0xc7, 0x4e, 0x4d, 0x9a, 0xd5,
	0x42, 0x44, 0x1e, 0xd2, 0x80, 0x38, 0xab, 0x2a, 0xb2, 0xf8, 0x16, 0x0c, 0x2a, 0x2f, 0xa7, 0xae,
	0x18, 0x92, 0x2c, 0x9f, 0x40, 0xe3, 0x22, 0x8c, 0xf9, 0x65, 0x80, 0x67, 0x4e, 0x63, 0x69, 0xf7,
	0x52, 0x2c, 0x7a, 0x08, 0x75, 0x12, 0xe1, 0x8b, 0x31, 0x09, 0x9c, 0xa6, 0xec, 0x95, 0x31, 0x5c,
	0x87, 0xca, 0xe1, 0x6b, 0x04, 0x6a, 0x43, 0x35, 0x0c, 0x1c, 0x90, 0x35, 0xaf, 0x86, 0x01, 0x7a,
	0x6a, 0xce, 0x66, 0x6b, 0x69, 0xd4, 0x0c, 0x2c, 0x76, 0x4e, 0x27, 0x41, 0xb2, 0x73, 0x6d, 0xf9,
	0xce, 0x14, 0xec, 0xf5, 0xc0, 0x3e, 0x0e, 0x19, 0x47, 0x5f, 0x82, 0x1d, 0x60, 0x8e, 0x9d, 0x8a,
	0xbc, 0x62, 0xc6, 0x84, 0xe9, 0xc6, 0xf9, 0xd2, 0xef, 0xed, 0x40, 0xeb, 0xec, 0x92, 0xde, 0x68,
	0x75, 0x50, 0x47, 0xa8, 0xe8, 0x23, 0x78, 0x4f, 0x60, 0x4d, 0xb9, 0xd9, 0x84, 0x46, 0x8c, 0x18,
	0xb4, 0x95, 0x85, 0xb4, 0x5f, 0xc1, 0x9d, 0x13, 0xd9, 0x3b, 0x4d, 0x7c, 0xcb, 0xfd, 0xf5, 0x9e,
	0x42, 0x5b, 0x03, 0x3f, 0x32, 0x04, 0x86, 0xee, 0x09, 0x0d, 0xc2, 0x77, 0xb3, 0x53, 0xcc, 0xd8,
	0x2d, 0xf9, 0xa3, 0x3d, 0x68, 0xd1, 0x71, 0x20, 0x10, 0x37, 0x34, 0x0e, 0x92, 0x61, 0x34, 0x4d,
	0x62, 0x1e, 0x27, 0xda, 0x9d, 0xcc, 0xa3, 0x5e, 0x7b, 0x3d, 0x40, 0x66, 0x88, 0x24, 0x41, 0x07,
	0xea, 0x6c, 0x3a, 0x1c, 0x12, 0xc6, 0x64, 0xa0, 0x86, 0xaf, 0x97, 0xde, 0x6f, 0x70, 0x4f, 0xe1,
	0xf3, 0x67, 0x2f, 0x26, 0xb5, 0x0d, 0x4d, 0x3a, 0x0e, 0x14, 0x26, 0x49, 0x29, 0x33, 0x18, 0x95,
	0xb2, 0x72, 0x95, 0x7a, 0x0c, 0xeb, 0x79, 0xf2, 0xa5, 0xe9, 0xfc, 0x00, 0x1d, 0x9f, 0x30, 0xc2,
	0x17, 0x15, 0xc8, 0x3c, 0x7e, 0xb5, 0x70, 0xfc, 0x47, 0xd0, 0x35, 0xf6, 0x2f, 0x0d, 0xf7, 0x2b,
	0x74, 0x04, 0xf2, 0x98, 0x8e, 0xc2, 0x48, 0x87, 0x43, 0x60, 0x8b, 0xde, 0x69, 0x75, 0x10, 0xdf,
	0x8b, 0x42, 0x1a, 0xf7, 0xd7, 0x32, 0xef, 0xaf, 0xf7, 0x3d, 0x74, 0x0d, 0xee, 0x24, 0x95, 0xe2,
	0x59, 0x8c, 0xd4, 0xaa, 0xf9, 0xd4, 0x6e, 0x60, 0x43, 0x57, 0x6d, 0x14, 0x32, 0x4e, 0x62, 0x23,
	0xbf, 0x92, 0x7a, 0x65, 0x0d, 0xa8, 0xe6, 0x54, 0x68, 0xc1, 0xa4, 0x18, 0x79, 0xdb, 0xb9, 0xbc,
	0x5f, 0xc0, 0x66, 0x31, 0xf0, 0x47, 0x27, 0xff, 0x39, 0xdc, 0x7d, 0x15, 0x46, 0xc1, 0x51, 0x74,
	0x14, 0x14, 0xbb, 0x68, 0x25, 0xd7, 0xf4, 0x11, 0xdc, 0x53, 0x90, 0xdb, 0x2f, 0x9d, 0x65, 0x8c,
	0x52, 0x1f, 0x36, 0x04, 0xfc, 0x38, 0xbc, 0x22, 0x1f, 0x76, 0x4b, 0x1f, 0x42, 0x57, 0x6c, 0x38,
	0x53, 0xf7, 0x2f, 0x03, 0x27, 0x67, 0xae, 0xe4, 0xce, 0x9c, 0x80, 0x3f, 0x8c, 0xf9, 0x1e, 0x74,
	0x15, 0xab, 0x7c, 0xf5, 0x14, 0xd8, 0xdb, 0x07, 0x64, 0x1a, 0x93, 0x8a, 0x21, 0xb0, 0xf9, 0x6c,
	0xa2, 0xcf, 0x22, 0xbf, 0xbd, 0x2d, 0xa8, 0x9f, 0x10, 0xc6, 0xc4, 0x9b, 0xd7, 0x01, 0x8b, 0xe1,
	0xf4, 0x91, 0x65, 0x78, 0xf6, 0x60, 0x07, 0x1a, 0xfa, 0x3d, 0x45, 0x75, 0xb0, 0x9e, 0x9f, 0x1d,
	0x74, 0x56, 0x50, 0x03, 0xec, 0x97, 0x87, 0x67, 0x07, 0x9d, 0xea, 0x03, 0x17, 0xea, 0x89, 0x84,
	0xa3, 0x55, 0xa8, 0xfe, 0x4c, 0x3b, 0x2b, 0x02, 0xf5, 0x0b, 0x61, 0x9d, 0xca, 0xe0, 0xdf, 0x06,
	0xd8, 0x6f, 0xc5, 0xb0, 0xf6, 0xa1, 0x76, 0x14, 0x05, 0xe4, 0x0f, 0xb4, 0x9e, 0x09, 0x51, 0xf6,
	0x24, 0xbb, 0xed, 0xcc, 0x2a, 0x64, 0xd7, 0x5b, 0x41, 0xdf, 0x82, 0x2d, 0x14, 0x13, 0x6d, 0x18,
	0x8f, 0x7a, 0x26, 0xb0, 0xee, 0x66, 0xd1, 0xac, 0x0e, 0xe7, 0xad, 0xa0, 0x1f, 0xa1, 0xf9, 0x9a,
	0xf0, 0x44, 0x04, 0x3e, 0xc9, 0x60, 0xb9, 0x3a, 0xba, 0x4e, 0xd9, 0x91, 0x32, 0xbc, 0xcd, 0xb4,
	0x54, 0x0d, 0x1b, 0xda, 0x2d, 0xa3, 0x73, 0xf3, 0xef, 0xee, 0xdd, 0x0e, 0x48, 0x69, 0x4f, 0x04,
	0xad, 0x56, 0x41, 0x39, 0xed, 0x5b, 0xe6, 0xae, 0x82, 0x04, 0xbb, 0xdb, 0xf3, 0x9d, 0x29, 0xdd,
	0x4f, 0x70, 0x27, 0x55, 0x15, 0xa5, 0xc0, 0x39, 0x89, 0xcf, 0xc9, 0x95, 0xbb, 0x35, 0xd7, 0x97,
	0x72, 0xbd, 0x81, 0x35, 0x53, 0x13, 0xd1, 0x4e, 0x31, 0x76, 0xbe, 0x78, 0x9f, 0xdd, 0xe6, 0x4e,
	0x09, 0x5f, 0x41, 0x33, 0xd5, 0x19, 0x33, 0xb1, 0xa2, 0xb0, 0x99, 0x89, 0x95, 0x84, 0xc9, 0x5b,
	0x41, 0x87, 0x00, 0xd9, 0x1d, 0x30, 0xeb, 0x55, 0xba, 0x19, 0x0b, 0x3b, 0xfa, 0x1a, 0x50, 0xfe,
	0xa2, 0xca, 0xb7, 0x7d, 0x37, 0x4f, 0x57, 0xba, 0xc6, 0x73, 0xa6, 0xf2, 0x00, 0x3a, 0xa6, 0x40,
	0x48, 0x9a, 0x9d, 0x3c, 0x4d, 0x41, 0x3c, 0xe6, 0x90, 0x7c, 0x07, 0x6b, 0x89, 0x10, 0xbd, 0x94,
	0x04, 0x9f, 0x16, 0x09, 0x52, 0x81, 0x9a, 0xb3, 0xf9, 0x19, 0xb4, 0x33, 0x09, 0x91, 0xdb, 0x0b,
	0x55, 0xc9, 0x89, 0xcb, 0x1c, 0x82, 0x13, 0x68, 0x67, 0xa2, 0x50, 0x24, 0x28, 0x69, 0x88, 0x39,
	0x86, 0x65, 0x2d, 0x91, 0x87, 0x81, 0xec, 0xe7, 0x4a, 0x8e, 0xaa, 0xf8, 0x23, 0xa6, 0x9c, 0xcb,
	0xc5, 0xaa, 0xfc, 0x27, 0xec, 0x9b, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x6e, 0x24, 0x6c, 0xca,
	0xa5, 0x0d, 0x00, 0x00,
}
