// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/user/user.proto

package srv_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for User service

type UserService interface {
	Index(ctx context.Context, in *Pagination, opts ...client.CallOption) (*UserList, error)
	FindMobile(ctx context.Context, in *RegisterRequest, opts ...client.CallOption) (*RegisterResponse, error)
	FindEmail(ctx context.Context, in *RegisterRequest, opts ...client.CallOption) (*RegisterResponse, error)
	FindID(ctx context.Context, in *RegisterRequest, opts ...client.CallOption) (*RegisterResponse, error)
	CreateMobile(ctx context.Context, in *RegisterRequest, opts ...client.CallOption) (*RegisterResponse, error)
	CreateEmail(ctx context.Context, in *RegisterRequest, opts ...client.CallOption) (*RegisterResponse, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) Index(ctx context.Context, in *Pagination, opts ...client.CallOption) (*UserList, error) {
	req := c.c.NewRequest(c.name, "User.Index", in)
	out := new(UserList)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) FindMobile(ctx context.Context, in *RegisterRequest, opts ...client.CallOption) (*RegisterResponse, error) {
	req := c.c.NewRequest(c.name, "User.FindMobile", in)
	out := new(RegisterResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) FindEmail(ctx context.Context, in *RegisterRequest, opts ...client.CallOption) (*RegisterResponse, error) {
	req := c.c.NewRequest(c.name, "User.FindEmail", in)
	out := new(RegisterResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) FindID(ctx context.Context, in *RegisterRequest, opts ...client.CallOption) (*RegisterResponse, error) {
	req := c.c.NewRequest(c.name, "User.FindID", in)
	out := new(RegisterResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) CreateMobile(ctx context.Context, in *RegisterRequest, opts ...client.CallOption) (*RegisterResponse, error) {
	req := c.c.NewRequest(c.name, "User.CreateMobile", in)
	out := new(RegisterResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) CreateEmail(ctx context.Context, in *RegisterRequest, opts ...client.CallOption) (*RegisterResponse, error) {
	req := c.c.NewRequest(c.name, "User.CreateEmail", in)
	out := new(RegisterResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for User service

type UserHandler interface {
	Index(context.Context, *Pagination, *UserList) error
	FindMobile(context.Context, *RegisterRequest, *RegisterResponse) error
	FindEmail(context.Context, *RegisterRequest, *RegisterResponse) error
	FindID(context.Context, *RegisterRequest, *RegisterResponse) error
	CreateMobile(context.Context, *RegisterRequest, *RegisterResponse) error
	CreateEmail(context.Context, *RegisterRequest, *RegisterResponse) error
}

func RegisterUserHandler(s server.Server, hdlr UserHandler, opts ...server.HandlerOption) error {
	type user interface {
		Index(ctx context.Context, in *Pagination, out *UserList) error
		FindMobile(ctx context.Context, in *RegisterRequest, out *RegisterResponse) error
		FindEmail(ctx context.Context, in *RegisterRequest, out *RegisterResponse) error
		FindID(ctx context.Context, in *RegisterRequest, out *RegisterResponse) error
		CreateMobile(ctx context.Context, in *RegisterRequest, out *RegisterResponse) error
		CreateEmail(ctx context.Context, in *RegisterRequest, out *RegisterResponse) error
	}
	type User struct {
		user
	}
	h := &userHandler{hdlr}
	return s.Handle(s.NewHandler(&User{h}, opts...))
}

type userHandler struct {
	UserHandler
}

func (h *userHandler) Index(ctx context.Context, in *Pagination, out *UserList) error {
	return h.UserHandler.Index(ctx, in, out)
}

func (h *userHandler) FindMobile(ctx context.Context, in *RegisterRequest, out *RegisterResponse) error {
	return h.UserHandler.FindMobile(ctx, in, out)
}

func (h *userHandler) FindEmail(ctx context.Context, in *RegisterRequest, out *RegisterResponse) error {
	return h.UserHandler.FindEmail(ctx, in, out)
}

func (h *userHandler) FindID(ctx context.Context, in *RegisterRequest, out *RegisterResponse) error {
	return h.UserHandler.FindID(ctx, in, out)
}

func (h *userHandler) CreateMobile(ctx context.Context, in *RegisterRequest, out *RegisterResponse) error {
	return h.UserHandler.CreateMobile(ctx, in, out)
}

func (h *userHandler) CreateEmail(ctx context.Context, in *RegisterRequest, out *RegisterResponse) error {
	return h.UserHandler.CreateEmail(ctx, in, out)
}
